name: Release Pipeline

on:
  push:
    branches:
      - main

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Run Release Please
        uses: googleapis/release-please-action@v5
        with:
          token: ${{ secrets.RELEASE_BOT_PAT }}
